services:
  proxy:
    image: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - $CADDY:/etc/caddy
  app:
    build:
      dockerfile: ./docker/app/Dockerfile
  api:
    build:
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - $DB_FILE:/app/api.db
